<?php

define('STORY_MAP_STORY_INDEX_PATH', 'admin/content/stories');

/**
 * Implements hook_menu().
 */
function story_map_menu() {
  $items = array();

  $items['admin/config/story-map'] = array(
    'title' => 'Story map',
    'description' => 'Story map global configuration.',
    'position' => 'right',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/config/story-map/manage'] = array(
    'title' => 'Manage Story map configuration.',
    'description' => 'Manage active Tilestache configuration.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('story_map_config_manage_form'),
    'file' => 'story_map.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function story_map_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'node/add' on 'admin/content' page.
  if ($root_path == STORY_MAP_STORY_INDEX_PATH) {
    $item = menu_get_item('story/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_permission().
 */
function story_map_permission() {
  return array(
    'view stories' => array(
      'title' => t('View stories'),
    ),
    'create stories' => array(
      'title' => t('Create stories'),
    ),
    'update stories' => array(
      'title' => t('Edit stories'),
    ),
    'delete stories' => array(
      'title' => t('Delete stories'),
    ),
  );
}

/**
 * Implements hook_ctools_plugin_api().
 */
function story_map_ctools_plugin_api($module, $api) {
  if ($module == "openlayers") {
    switch ($api) {
      case 'openlayers_layers':
        return array('version' => 1);
    }
  }
}

/**
 * Implements hook_entity_info().
 */
function story_map_entity_info() {
  $info['story_map_story'] = array(
    'label' => t('Story'),
    'plural label' => t('Stories'),
    'controller class' => 'EntityAPIControllerExportable',
    'metadata controller class' => FALSE,
    'entity class' => 'StoryMapStory',
    'base table' => 'story_map_story',
    'module' => 'story_map',
    'bundles' => array(),
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name',
      'name' => 'machine_name',
    ),
    'access callback' => 'story_map_story_access',
    'admin ui' => array(
      'path' => 'story',
      'file' => 'story_map.admin.inc',
      'controller class' => 'StoryMapStoryUIController',
      'menu wildcard' => '%story_map_story',
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
  );

  return $info;
}

/**
 * Implements hook_entity_info_alter().
 */
function story_map_entity_info_alter(&$entity_info) {
  $view_mode = array(
    'label' => t('Story map story popup'),
    'custom settings' => FALSE,
  );
  foreach ($entity_info as $entity => &$info) {
    if (isset($info['view modes']) && !empty($info['view modes'])) {
      $info['view modes']['story_map_story_popup'] = $view_mode;
    }
  }
}

/**
 * Implements hook_entity_property_info().
 */
function story_map_entity_property_info() {
  $info['story_map_story']['properties'] = array(
    'id' => array(
      'label' => t('ID'),
      'type' => 'integer',
      'description' => t('The primary identifier for a story.'),
      'schema field' => 'id',
      'validation callback' => 'entity_metadata_validate_integer_positive',
    ),
    'name' => array(
      'label' => t('Name'),
      'type' => 'text',
      'description' => t('The displayed name for a story.'),
      'schema field' => 'name',
      'required' => TRUE,
    ),
    'machine_name' => array(
      'label' => t('Machine name'),
      'type' => 'token',
      'description' => t('The internally used machine name for a story.'),
      'schema field' => 'machine_name',
      'required' => TRUE,
    ),
    'queue' => array(
      'label' => t('Story queue'),
      'type' => 'text',
      'description' => t('The internally used machine name referencing an existing node queue.'),
      'schema field' => 'queue',
      'required' => TRUE,
    ),
    'description' => array(
      'label' => t('Description'),
      'type' => 'text',
      'description' => t('The displayed description of a story.'),
      'schema field' => 'description',
      'sanitize' => 'filter_xss',
    ),
    /*
    'options' => array(
    
    ),
     */
    'enabled' => array(
      'label' => t('Enabled'),
      'type' => 'boolean',
      'description' => t('A flag indicating whether the story is enabled.'),
      'schema field' => 'enabled',
    ),
  );

  return $info;
}

/**
 * Access callback for story entity operations.
 */
function story_map_story_access($op, $entity_info = NULL, $account = NULL) {
  switch ($op) {
    case 'view':
    case 'create':
    case 'update':
    case 'delete':
      return user_access($op . " stories", $account);

    default:
      return user_access('administer content', $account);
  }
}

/**
 * Determine if the machine name is in use.
 */
function story_map_story_machine_name_exists($machine_name) {
  $query = 'SELECT 1 FROM {story_map_story} WHERE machine_name = :machine_name';
  $exists = db_query_range($query, 0, 1, array(':machine_name' => $machine_name))->fetchField();
  return $exists;
}


function story_map_story_load($name) { 
  return story_map_get_stories($name);
}

function story_map_get_stories($name = NULL) {
  $stories = entity_load_multiple_by_name('story_map_story', isset($name) ? array($name) : FALSE);
  return isset($name) ? reset($stories) : $stories;
}

/**
 * Implements hook_story_map_story_presave().
 */
function story_map_story_map_story_presave($story) {
  $story->refreshQueue();
}

/**
 * Implements hook_story_map_story_delete().
 */
function story_map_story_map_story_delete($story) {
  nodequeue_delete($story->getQueue()->qid);
}

/**
 * Implements hook_story_map_story_view().
 * Prepares features stored in nodequeue and passes them to the openlayers map.
 */
function story_map_story_map_story_view($story, $view_mode, $langcode) {
  $path = drupal_get_path('module', 'story_map');

  foreach (entity_metadata_wrapper("list<node>", $story->getQueueNodes()) as $index => $wrapper) {
    $geofield = story_map_get_default_geofields($wrapper->getBundle());

    if (!isset($wrapper->{$geofield})) {
      continue;
    }

    $geodata = $wrapper->{$geofield}->value();

    // Skip item id geodata is empty/invalid.
    if (empty($geodata)) {
      // TODO: Handle error?
      debug('ERROR: Invalid/empty geodata for node: ' . $wrapper->getIdentifier());
      continue;
    }

    $build = node_view($wrapper->value(), 'story_map_story_popup');
    $content = drupal_render($build);

    $story->getMap()->addFeature($geodata, $content);
  }

  drupal_alter('story_map_view', $story);

  $story->content['map']['#markup'] = $story->getMap()->render();
}

/**
 * Implements hook_openlayers_behaviors().
 */
function story_map_openlayers_behaviors() {
  return array(
    'openlayers_behavior_story_map' => array(
      'title' => t('Story map'),
      'description' => t(''),
      'behavior' => array(
        'path' => drupal_get_path('module', 'story_map') .'/behaviors',
        'file' =>  'openlayers_behavior_story_map.inc',
        'class' => 'OpenLayersBehaviourStoryMap',
        'parent' => 'openlayers_behavior',
      ),
    ),
  );
}

/**
 * Implements hook_openlayers_layers().
 */
function story_map_openlayers_layers() {
  $layer = new stdClass();

  $layer->api_version = 1;
  $layer->name = 'openlayers_behavior_story_map_story_data';
  $layer->title = t('Story map story data.');
  $layer->description = t('Placeholder layer for map story data.');

  $layer->data = array(
    'projection' => array('4326'),
    'layer_type' => 'openlayers_layer_type_raw',
    'options' => array(
      'layers' => array(),
    ),
  );

  return array($layer->name => $layer);
}

/**
 * Returns the default geofield to use with the specified content type.
 * Returns FALSE if the specified content type hasn't had a geofield configured.
 */
function story_map_get_default_geofields($type = NULL) {
  $fields = &drupal_static(__FUNCTION__);

  if (!isset($fields)) {
    $fields = variable_get('story_map_geofields', array());
  }

  if ($type) {
    return isset($fields[$type]) ? $fields[$type] : FALSE;
  }

  return $fields;
}

/**
 * Returns an array keyed by node types that have one or more geofields
 * attached. Each item is an array containing the names of the geofields 
 * attached to that node type.
 */
function story_map_get_all_geofields() {
  $fields = array();
  foreach (field_info_fields() as $name => $info) {
    if ($info['type'] == 'geofield') {
      if (isset($info['bundles']['node'])) {
        foreach ($info['bundles']['node'] as $type) {
          $fields[$type][$name] = $name;
        }
      }
    }
  }

  return $fields;
}

function story_map_driver_info() {
  $drivers = &drupal_static(__FUNCTION__);
  if (!isset($drivers)) {
    $drivers = module_invoke_all('story_map_driver_info');
  }
  drupal_alter('story_map_driver_info', $drivers);

  return $drivers;
}

/**
 * Implements hook_story_map_driver_info().
 */
function story_map_story_map_driver_info() {
  $path = drupal_get_path('module', 'story_map');
  return array(
    'leaflet' => array(
      'class' => 'LeafletStoryMap',
      'file' => $path . '/includes/leaflet_story_map.inc',
    ),
    'openlayers' => array(
      'class' => 'OpenlayersStoryMap',
      'file' => $path . '/includes/openlayers_story_map.inc',
    ),
  );
}

/**
 * Load a map driver.
 */
function story_map_create_map($compound_name) {
  $drivers = story_map_driver_info();
  list($library, $name) = explode('::', $compound_name, 2);

  if (isset($drivers[$library])) {
    require_once DRUPAL_ROOT . '/' . $drivers[$library]['file'];
    return new $drivers[$library]['class']($name);
  }
  else {
    throw new Exception(); // TODO: Name this.
  }
}
